version: '3.8'
services:
  minio:
    image: 'minio/minio:latest'
    container_name: minio
    hostname: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./minio/data:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_API_SELECT_PARQUET: "on"
    command: [ "server", "/data", "--console-address", ":9001" ]
    networks:
      - likehouse_network
  
  clickhouse:
    image: bitnami/clickhouse:23.4.2-debian-11-r7
    container_name: clickhouse
    hostname: clickhouse
    ports:
     - "8123:8123"
     - "9009:9009"
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - likehouse_network

networks:
  likehouse_network:
    external: true