version: '3.8'
services:
  mariadb:
    image: mariadb:10.11.10
    container_name: mariadb
    hostname: hive-metastore-db
    volumes:
      - ./hive-metastore/data:/var/lib/mysql
    ports:
      - 3306:3306
    env_file:
      - .env
    networks:
      - likehouse_network

  hive-metastore:
    build:
      context: ./hive-metastore
      dockerfile: ./Dockerfile
    container_name: hive-metastore
    hostname: hive-metastore
    entrypoint: /entrypoint.sh
    ports:
      - "9083:9083"
    volumes:
      - ./hive-metastore/metastore-site.xml:/opt/apache-hive-metastore-3.0.0-bin/conf/metastore-site.xml:ro
    environment:
      METASTORE_DB_HOSTNAME: mariadb
    networks:
      - likehouse_network
    depends_on:
      - mariadb

  spark-master:
    build:
      context: ./spark
      dockerfile: ./Dockerfile
    container_name: spark-master
    ports:
      - 7077:7077
      - 8081:8080
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    volumes:
      - ./spark/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
    networks:
      - likehouse_network

  spark-worker-1:
    image: docker.io/bitnami/spark:3.3
    container_name: spark-worker-1
    env_file:
      - .env
    depends_on:
      - spark-master
    networks:
      - likehouse_network

  spark-worker-2:
    image: docker.io/bitnami/spark:3.3
    container_name: spark-worker-2
    env_file:
      - .env
    depends_on:
      - spark-master
    networks:
      - likehouse_network

  spark-thrift-server:
    build:
      context: ./spark
      dockerfile: ./Dockerfile
    container_name: spark-thrift-server
    restart: always
    depends_on:
      - spark-master
      - hive-metastore
    ports:
      - 4040:4040
      - 10000:10000
    command: sh -c "
      sleep 10 && ./sbin/start-thriftserver.sh --driver-java-options '-Dhive.metastore.uris=thrift://hive-metastore:9083' --master spark://spark-master:7077      --executor-memory 4G --total-executor-cores 4 --driver-memory 4G"
    volumes:
      - ./spark/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
      - ./spark/hive-site.xml:/opt/bitnami/spark/conf/hive-site.xml
    networks:
      - likehouse_network

networks:
  likehouse_network:
    external: true