version: '3.8'
services:
  minio:
    image: minio/minio:latest
    container_name: minio
    hostname: minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./minio/data:/data
    env_file:
      - .env
    command: [ "server", "/data", "--console-address", ":9001" ]
    networks:
      - likehouse_network
  
  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: clickhouse-server
    hostname: clickhouse-server
    ports:
     - 18123:8123
     - 19000:9000
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./clickhouse/data:/var/lib/clickhouse
      - ./clickhouse/logs:/var/log/clickhouse-server
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - IPC_LOCK
      - SYS_PTRACE
    networks:
      - likehouse_network

networks:
  likehouse_network:
    external: true