dbtSpark:
  target: dev
  outputs:
    dev:
      host: spark-thrift-server
      method: thrift
      port: 10000
      user: root
      schema: dev
      threads: 6
      type: spark
      connect_retries: 5
      connect_timeout: 60
      retry_all: true